platform:ios, ‘9.0‘


target :masonry布局 do
    
    pod 'AFNetworking'
    
    pod 'FMDB'
    
    pod 'MJExtension'
    
    pod 'MBProgressHUD', '~> 1.0.0'
    
    pod 'Masonry'
    
    pod 'SDWebImage'

end







